### ISSUE TITLE
uwsgi-piku.service not being enabled?

### ISSUE THREAD

**Issue by jfmatth** [piku/piku-bootstrap#9]
Hi, love the project, thank you for building it.

I was wondering why after a reboot my sites didn't work, and found that the uwsgi-piku.service wasn't being enabled, but by all accounts in the playbook it should be.  Very odd.

I was using Proxmox containers, thinking that might be the issue, but then tried it on a new 22.04 Ubuntu VM on proxmox, same result.

The Ansible playbook shows it's changed, but the systemctl status shows otherwise after the run 

```
TASK [Enable uwsgi-piku service] ***************************************************************************************************************************
changed: [127.0.0.1]

TASK [Start uwsgi init script] *****************************************************************************************************************************
skipping: [127.0.0.1]

TASK [Get nginx default config] ****************************************************************************************************************************
changed: [127.0.0.1]

TASK [Restart nginx service] *******************************************************************************************************************************
changed: [127.0.0.1]

TASK [Get systemd.path piku-nginx.path] ********************************************************************************************************************
changed: [127.0.0.1]

TASK [Get systemd.path piku-nginx.service] *****************************************************************************************************************
changed: [127.0.0.1]

TASK [Start piku-nginx.path] *******************************************************************************************************************************
changed: [127.0.0.1]

PLAY RECAP *************************************************************************************************************************************************
127.0.0.1                  : ok=33   changed=27   unreachable=0    failed=0    skipped=2    rescued=0    ignored=1

jfmatth@vm-piku-1:~$ systemctl status uwsgi-piku.service
● uwsgi-piku.service - Piku uWSGI Emperor
     Loaded: loaded (/etc/systemd/system/uwsgi-piku.service; disabled; vendor preset: enabled)
     Active: active (exited) since Wed 2023-08-02 15:22:49 UTC; 10s ago
        CPU: 16ms
```

Any thoughts on how to troubleshoot this?

Not sure if it matters, but I'm running SUDO instead of from the root account.

Just tried this on a DO droplet for 22.04, same result and I'm logged in as root.

After install, if I reboot the service isn't starting.  If I then enable it, reboot, it works as expected.

**Comment by jfmatth** [comment]
seeing odd behavior in the journal on install, mentioning the uwsgi-piku.service is world-inaccessible, maybe that's it?

```
Aug 02 16:12:06 ct-piku-2 systemd[1]: Configuration file /etc/systemd/system/uwsgi-piku.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Aug 02 16:12:06 ct-piku-2 systemd[1]: Configuration file /etc/systemd/system/uwsgi-piku.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Aug 02 16:12:06 ct-piku-2 systemd[1]: Configuration file /etc/systemd/system/uwsgi-piku.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
Aug 02 16:12:06 ct-piku-2 systemd[1]: Starting LSB: starts the uwsgi app server...
Aug 02 16:12:06 ct-piku-2 uwsgi-piku[5401]: Starting uwsgi-piku:
Aug 02 16:12:06 ct-piku-2 sudo[5408]:     root : PWD=/home/piku ; USER=piku ; COMMAND=/bin/sh -c uwsgi-piku --ini \/home\/piku\/\.piku\/uwsgi\/uwsgi\.ini --daemonize \/home\/piku\/\.piku\/uwsgi\/uwsgi\.log --pidfile \/home\/piku\/\.piku\/uwsgi\/uwsgi-piku\.pid
Aug 02 16:12:06 ct-piku-2 sudo[5408]: pam_limits(sudo-i:session): Could not set limit for 'core' to soft=0, hard=-1: Operation not permitted; uid=0,euid=0
Aug 02 16:12:06 ct-piku-2 sudo[5408]: pam_unix(sudo-i:session): session opened for user piku(uid=1000) by (uid=0)
Aug 02 16:12:06 ct-piku-2 systemd[1]: Created slice User Slice of UID 1000.
Aug 02 16:12:06 ct-piku-2 systemd[1]: Starting User Runtime Directory /run/user/1000...
Aug 02 16:12:06 ct-piku-2 systemd[1]: Finished User Runtime Directory /run/user/1000.
Aug 02 16:12:06 ct-piku-2 systemd[1]: Starting User Manager for UID 1000...
```

**Comment by chr15m** [comment]
Hi, thanks for reporting this. Seems very weird. I'll try to find some time to investigate and if you discover anything to fix it in the mean time let me know.

**Comment by jfmatth** [comment]
I'm wondering if the file settings have anything to do with it?

Seems odd.  It starts the service but doesn't enable it.  Maybe an Ansible bug?

I solve it by manually setting it to enabled

**Comment by chr15m** [comment]
When you say you set it to enabled, do you recall the command? Or did you do it with Ansible, and if so could you send me the change? Could be file settings - maybe there needs to be a step before where it does chmod or something.

**Comment by jfmatth** [comment]
Sadly, not Ansible, just systemctl

```
systemctl enable uwsgi-piku.service --now
```

**Comment by jfmatth** [comment]
Also, I'm noticing that UWSGI albeit working is not supported anymore :(.

Any thoughts on moving to say gunicorn?  Probably a lot of work unfortunately.

**Comment by chr15m** [comment]
Yeah that's a big job. I guess @rcarmo would have more to say on this as the creator or Piku. My preference would be to go for something lighter than uwsgi that is not bound to Python, perhaps even just using systemd to keep the web processes alive and connect nginx to them.

**Comment by chr15m** [comment]
@jfmatth ok I found the problem. In your playbook it says "`Start uwsgi init script`" but that rule should only be reached if `"systemctl" not in systemctl.stdout`. So for some reason the systemctl command is not being found correctly. Flagging this as a bug.

**Comment by rcarmo** [comment]
@jfmath Why do you say `uWSGI` is not supported? it is still being maintained (has commits from this week), and the only reason to move off it right now would be if it were dropped from both Debian and Ubuntu (which seems unlikely given that I see it listed for all known future releases of both...). I've been toying with the idea of using `caddy` (and replace `nginx` as well), but to be honest the ease with which we can get `uWSGI` to supervise processes for any language runtime still trumps It, but I'm curious as to why you have that impression.

**Comment by jfmatth** [comment]
Found this, but not sure it's still a bug in Ansible?

https://github.com/ansible/ansible/issues/72451

**Comment by jfmatth** [comment]
I wonder if you should specify the full path to the systemd package?  

I use the systemd module in some of my playbooks, but I specify the full module name
```
    - name: Start qemu-guest-agent
      ansible.builtin.systemd:
        name: qemu-guest-agent
        enabled: true
        state: started
```

I'm pretty sure my code works on the same Ubuntu 22.04 targets

I'll do some checking on my side to see if that fixes it.

**Comment by chr15m** [comment]
Cool thanks for testing. If you fork this repo and push your changes to your fork then the GitHub action will run and tell you if it failed on any other versions of Ubuntu.

**Comment by chr15m** [comment]
By the way I noticed on that bug you linked that they use the following workaround. This could be useful if the Ansible bug is in Ubuntu distribution of Ansible itself.

```
# https://github.com/ansible/ansible/issues/72451
- name: Really enable postgresql
  shell:
    cmd: "systemctl enable postgresql@12-main.service"
  when: postgresql_systemd.status.UnitFileState == 'enabled-runtime'
```

(We would have to swap out postgres for uwsgi).

**Comment by jfmatth** [comment]
> I wonder if you should specify the full path to the systemd package?
> 
> I use the systemd module in some of my playbooks, but I specify the full module name
> 
> ```
>     - name: Start qemu-guest-agent
>       ansible.builtin.systemd:
>         name: qemu-guest-agent
>         enabled: true
>         state: started
> ```
> 
> I'm pretty sure my code works on the same Ubuntu 22.04 targets
> 
> I'll do some checking on my side to see if that fixes it.

Unfortunately, using the module name fully didn't seem to help.

I'm guessing at this point, its the "if" code in the task that is failing.  Ill check the playbook with the check removed and just have it enabled and let you know what happens.

Is there a reason we you are still supporting init.d?  seems like most systems are SystemD these days.

**Comment by jfmatth** [comment]
Ok **Weird Behavior**!

I was testing seeing if removing the "Test" for SystemD would make any difference, it didn't.

However, I thought I would run the install more than once, and that seemed to make it work?  The first time I ran it, it showed "Changed" on the "Enable uwsgi-piku service" task, ran it a second time, same thing, ran it a third time and it comes back green and the service is enabled and started.

Very strange!  I'm going to try to break the tasks out and separate enabled and started into two tasks like I do in my playbooks.  Stay tuned.

**Comment by jfmatth** [comment]
So strange, I broke out the enable and start into two seperate tasks and still the same behavior, i've never seen this with Ansible before :(

```
    - name: (new) Enable uwsgi-piku service
      systemd:
        name: uwsgi-piku
        enabled: yes

    - name: (new) Start uwsgi-piku service
      systemd:
        name: uwsgi-piku
        state: started
```

**Comment by jfmatth** [comment]
I even changed the file permissions to what was suggested on the net, 644, still not working as expected.

I'm stumped.

**Comment by chr15m** [comment]
Ok, thanks for your further testing!

**Comment by jfmatth** [comment]
of course.  All I can figure at this point is it's something do with how the service files are created?  I know that RH or Ubuntu have templates for that, maybe Ansible has a module to help with that?

**Comment by chr15m** [comment]
I've replicated this now on one of my own Piku machines. Thanks for reporting @jfmatth! I was wrong above when I said it starts the uwsgi init script - it is actually skipping that step (correctly) not running it.

**Comment by jfmatth** [comment]
Glad you were able to see it first hand @chr15m .

I looked over the Ansible playbook and from what I can tell, it should work, strange.

**Comment by chr15m** [comment]
Alright I managed to fix this using the workaround from here:

https://github.com/ansible/ansible/issues/72451#issuecomment-771541032

**Comment by chr15m** [comment]
I guess the version of Ansible in Ubuntu 22 contains the bug they talk about.

**Comment by chr15m** [comment]
Tested on a DO server that I spun up for this purpose.
